### ISSUE TITLE
cool

### ISSUE THREAD

**Issue by Forgiving0** [SheepTester/server-dancing#1]
Gunn.App EZ CLAP
But you registered an .app domain that's cool

**Comment by SheepTester** [comment]
gunn.app is actually @forevermilk's domain; he's hosting a server for it

sheep.thingkingland.app is a subdomain of my dad's domain, and supposedly whatever I host on this repo will show up there but https annoyances >.< so only https://github.com/SheepTester/web-server is really accessible
